SAMPLE_FREQUENCY = 0.5

DATA_BASE_PATH = 'data'
DATA_IDLE = 'idle'
DATA_IDLE_NUM = 1039
DATA_RUNNING = 'running'
DATA_RUNNING_NUM = 3408
DATA_STAIRS = 'stairs'
DATA_STAIRS_NUM = 165
DATA_WALKING = 'walking'
DATA_WALKING_NUM = 1850


ACTIVITY_LIST = [DATA_IDLE, DATA_STAIRS, DATA_RUNNING, DATA_WALKING]

DATA_SUMMARY = {
    DATA_IDLE: DATA_IDLE_NUM,
    DATA_WALKING: DATA_WALKING_NUM,
    DATA_RUNNING: DATA_RUNNING_NUM,
    DATA_STAIRS: DATA_STAIRS_NUM
}

FEATURE_COLUMNS = [
    'x_mean', 'y_mean', 'z_mean',
    'x_std', 'y_std', 'z_std',
    'x_peaks', 'y_peaks', 'z_peaks',
    'target'
]
